version: '3.4'
services:
  stash-sfw:
    image: stashapp/stash:latest
    container_name: stash-sfw
    restart: unless-stopped
    ports:
      - "9991:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro

      ## Keep configs here.
      - ./data-stash-sfw/config:/root/.stash

      ## Point this at your collection.
      - /mnt/virt/gdrive/crypt/Anime:/data/Anime
      - /mnt/virt/gdrive/crypt/Memes:/data/Memes

      ## This is where your stash's metadata lives
      - ./data-stash-sfw/metadata:/metadata

      ## Any other cache content.
      - ./data-stash-sfw/cache:/cache
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ./data-stash-sfw/generated:/generated

  stash:
    image: stashapp/stash:latest
    container_name: stash
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      
      ## Keep configs here.
      - /mnt/virt/gdrive/crypt/stash/stash/config:/root/.stash
      ## Point this at your collection.
      - /mnt/virt/gdrive/crypt/stash:/data
      - /mnt/virt/X:/data-x
      ## This is where your stash's metadata lives
      - /mnt/virt/gdrive/crypt/stash/stash/metadata:/metadata
      ## Any other cache content.
      - /mnt/virt/gdrive/crypt/stash/stash/cache:/cache
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /mnt/virt/gdrive/crypt/stash/stash/generated:/generated

      # Community Scrapers
      - /mnt/virt/gdrive/crypt/stash/stash/config/scrapers:/data/scrapers

  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9000
    ports:
      - 9099:9000
    volumes:
      - /mnt/virt/gdrive/crypt/stash/mango/mango:/root/mango
      - ./data-mango/config/mango:/root/.config/mango
