version: '3.3'
services:
  pms-docker:
    container_name: plex
    ports:
        - '32400:32400/tcp'
        - '3005:3005/tcp'
        - '8324:8324/tcp'
        - '32469:32469/tcp'
        - '1900:1900/udp'
        - '32410:32410/udp'
        - '32412:32412/udp'
        - '32413:32413/udp'
        - '32414:32414/udp'
    environment:
        - TZ=America/New_York
        - PLEX_CLAIM
        - 'ADVERTISE_IP=https://plex.thebritishaccent.net/,https://plex.tba.lan/,http://10.8.0.160:32400/'
    volumes:
        - './config-plex/config:/config'
        - './config-plex/transcode:/transcode'
        - '/mnt/virt:/data'     
    image: plexinc/pms-docker

  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Nassau
    volumes:
      - ./config-tautulli:/config
      - './logs-tautulli:/logs'
    ports:
      - 8282:8181
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Nassau
    #  - BASE_URL=/ombi #optional
    volumes:
      - ./config-ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped