---
version: "2"
services:
  komga:
    image: gotson/komga
    container_name: komga
    environment:
      - PUID=1000
      - PGID=1001
    volumes:
      - ./config:/config
      - /mnt/virt/manga:/books
      - /etc/timezone:/etc/timezone
    ports:
      - 8181:8080
    user: "1000:1000"
    restart: unless-stopped
